
GET http://localhost:3001/api/recettes

###

GET http://localhost:3001/api/recettes/4

###

GET http://localhost:3001/api/recettes/search/ta

###

POST http://localhost:3001/api/recettes
Content-Type: application/json

{
  "title": "Poulet au curry",
  "description": "Un bon poulet au curry.",
  "tempsDePreparation": 30,
  "tempsDeCuisson": 30,
  "ingredients": ["poulet","curry"],
  "instructions": ["Faire cuire le poulet dans le curry."],
  "image": "https://media.istockphoto.com/id/1157636229/fr/photo/tarte-aux-poires-aux-noix-et-tarte-au-miel-maison.jpg?s=1024x1024&w=is&k=20&c=opkpE1wKliJDPwp1YRc6aRjPKswFaHXdRVJC2khlHyQ=",
  "categorie": "Plat"

}

###

PUT http://localhost:3001/api/recettes/1
Content-Type: application/json

{
  "title": "Tarte aux poires",
  "tempsDePreparation": 30,
  "tempsDeCuisson": 30,
  "ingredients": ["pommes","pate à tarte"],
  "instructions": ["Mettre les pommes sur la pate et cuire au four."],
  "image": "https://media.istockphoto.com/id/1157636229/fr/photo/tarte-aux-poires-aux-noix-et-tarte-au-miel-maison.jpg?s=1024x1024&w=is&k=20&c=opkpE1wKliJDPwp1YRc6aRjPKswFaHXdRVJC2khlHyQ="
}

###

DELETE http://localhost:3001/api/recettes/1
