
GET http://localhost:3002/api/recettes

###

GET http://localhost:3002/api/recettes/4

###

GET http://localhost:3002/api/recettes/search/ta

###

GET http://localhost:3002/api/recette-du-jour

###

GET http://localhost:3002/api/recettes/page/1

###

POST http://localhost:3002/api/recettes
Content-Type: application/json



    {
      "idUser": 3,
      "title": "Pizza Margherita",
      "image": "https://www.example.com/pizza-margherita.jpg",
      "description": "Une délicieuse pizza classique à base de sauce tomate, de mozzarella et de basilic.",
      "tempsDePreparation": 15,
      "tempsDeCuisson": 20,
      "ingredients": ["Pâte à pizza", "Sauce tomate", "Mozzarella", "Basilic frais"],
      "instructions": ["Étalez la pâte à pizza", "Ajoutez la sauce tomate, la mozzarella et le basilic", "Cuisez au four jusqu'à ce que la croûte soit dorée"],
      "categorie": "Plat"
    }

###

PUT http://localhost:3002/api/recettes/2
Content-Type: application/json

{
  "image": "",
  
}

###

DELETE http://localhost:3002/api/recettes/1

###

GET http://localhost:3002/api/images
